name: Android Build Main

on:
  push:
    branches:
      - main


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Project on Main
        run: ./gradlew assemble

  unit_test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Tests on Main
        run: ./gradlew testDebugUnitTest --stacktrace #this runs unit tests only
        #run: ./gradlew test # this runs unit tests + ui tests


      - name: Generate Jacoco Test Reports
        run: ./gradlew jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv

  static_code_anaylsis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: detekt
        run: ./gradlew detekt --stacktrace