name: Android Build

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  #first setup the environment
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UP JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'


  build:
    needs: [setup_env]
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: ./gradlew assemble


  run_tests:
      needs: [setup_env]
      runs-on: ubuntu-latest
      steps:
        - name: Run Tests
          run: ./gradlew test
