name: Android CD release

on:
  push:
    branches:
      - release/*

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UP JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Generate apk
        run: ./gradlew clean assemble assembleDebug -p app
      - name: Upload Debug APK to Github
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Sample App Debug APK
          path: app/build/outputs/apk/debug/app*.apk
