name: Android CD release

on:
  push:
    branches:
      - release/*

jobs:
  apk_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UP JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Generate apk
        run: ./gradlew clean assemble assembleDebug -p app
      - name: Upload Debug APK to Github
        uses: actions/upload-artifact@v2.2.0
        with:
          name: NewsApp
          path: app/build/outputs/apk/debug/app*.apk
  build_and_distribute_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UP JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Project
        run: ./gradlew assemble

      - name: Create Firebase Service Credentials file
        run: |
            echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
            base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
            env:
              FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      - name: upload to firebase distribution
        run: ./gradlew appDistributionUploadDebug

  unit_test_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UP JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Tests
        run: ./gradlew testDebugUnitTest --stacktrace #this runs unit tests only
        #run: ./gradlew test # this runs unit tests + ui tests
